version: "3.9"
services:
  jac_backend:
    container_name: reseci_backend
    build: ./backend
    network_mode: host
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
  remix:
    container_name: reseci_frontend
    build: ./frontend
    network_mode: host
    volumes:
      - ./frontend/app:/usr/server/app/app
      - ./frontend/public:/usr/server/app/public
      - ./frontend/.env:/usr/server/app/.env
    ports:
      - "3000:3000"
#   traefik:
#     image: traefik:latest
#     ports:
#       - "80:80" # Expose port 80 on the host
#       - "443:443" # Expose port 443 on the host
#     volumes:
#       - "/var/run/docker.sock:/var/run/docker.sock:ro"
#       - ./letsencrypt:/letsencrypt
#     networks:
#       - sbm_network
#     command:
#       #- "--log.level=DEBUG"
#       - "--api.insecure=true"
#       - "--providers.docker=true"
#       - "--providers.docker.exposedbydefault=false"

#       # entrypoints
#       - "--entrypoints.jac_backend.address=:80"
#       - "--entrypoints.websecure.address=:443"

#       # let's encrypt
#       - "--certificatesresolvers.le.acme.email=admin@sbm.com"
#       - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
#       - "--certificatesresolvers.le.acme.tlschallenge=true"

#       # redirects
#       - "--entrypoints.jac_backend.http.redirections.entryPoint.to=websecure"
#       - "--entrypoints.jac_backend.http.redirections.entryPoint.scheme=https"
#       - "--entrypoints.jac_backend.http.redirections.entryPoint.permanent=true"
